version: '3'
services:
  front-end:
    build: ./front-end
    image: 617699280027.dkr.ecr.ap-southeast-1.amazonaws.com/front-end
    container_name: front-end
    expose:
      - "3000"
    depends_on:
      - back-end
    environment:
      - NODE_ENV=production
      - DESTINATION_API=http://52.78.182.5/
  back-end:
    build: ./back-end
    image: 617699280027.dkr.ecr.ap-southeast-1.amazonaws.com/backend-end
    container_name: back-end
    expose:
      - "7001"
  proxy-server:
    build: ./proxy-server
    image: 617699280027.dkr.ecr.ap-southeast-1.amazonaws.com/proxy-server
    container_name: proxy-server
    ports:
      - "80"
    depends_on:
      - front-end
    links:
      - front-end
      - back-end
