version: '3'
services:
  front-end:
    build: ./front-end
    image: front-end
    container_name: front-end
    expose:
      - "3000"
    depends_on:
      - back-end
    environment:
      - NODE_ENV=production
  back-end:
    build: ./back-end
    image: back-end
    container_name: back-end
    expose:
      - "7001"
  proxy-server: 
    build: ./proxy-server
    image: proxy-server
    container_name: proxy-server
    ports:
    - "80:80"
    depends_on:
      - front-end
