version: '3'
services:
  n2server:
    # image: localhost:5000/n2server
    image: "${ecr_base_url}/${service_name}"
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - DESTINATION_API=${DESTINATION_API}