import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
  PreviewData,
} from "next";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";
import Footer from "../src/components/layout/Footer";
import Header from "../src/components/layout/Header";
import SignIn from "../src/components/page/SignIn/SignIn";
import { WholeWrapper } from "../src/components/styles/CommonComponents";
import { UseLink } from "../src/configure/router.entity";

//SCSS

interface SignInProps {
  saveId: string;
  saveCheck: boolean;
}

/**
 * Index: 로그인 페이지
 * @param props
 * @returns
 */
const Home: NextPage<SignInProps> = (props) => {
  return (
    <>
      <Head>
        <title>MK SOLUTION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WholeWrapper minHeight={`100vh`} ju={`space-between`}>
        <Header />
        <SignIn {...props} />
        <Footer />
      </WholeWrapper>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext<ParsedUrlQuery, PreviewData>
) => {
  // 쿠키 확인 - 아이디 저장, props로 전달(있을 경우 : 쿠키 / 없을 경우 : "")
  const saveId: string = context.req.cookies.saveId
    ? context.req.cookies.saveId
    : ""; // 저장된 아이디(id)
  const saveCheck: boolean = context.req.cookies.saveId ? true : false; // 저장 여부(boolean)
  // 토큰 확인 - 있을 경우, 메인 화면으로 리디렉트
  if (context.req.cookies.mk_token) {
    return {
      redirect: {
        permanent: false,
        destination: UseLink.MAIN,
      },
    };
  }
  return {
    props: {
      saveId,
      saveCheck,
    },
  };
};
