import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../src/components/layout/Footer";
import Header from "../src/components/layout/Header";
import { WholeWrapper } from "../src/components/styles/CommonComponents";
import SignUp from "../src/components/page/SignUp";

const SignUpPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>MK SOLUTION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WholeWrapper minHeight={`100vh`} ju={`space-between`}>
        <Header />
        <SignUp />
        <Footer />
      </WholeWrapper>
    </>
  );
};

export default SignUpPage;
