import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../src/components/layout/Footer";
import Header from "../../src/components/layout/Header";
import { WholeWrapper } from "../../src/components/styles/CommonComponents";
import SignUp from "../../src/components/page/SignUp";
import { useRouter } from "next/dist/client/router";
import { MainRoute } from "../../src/models/router.entity";
import Find from "../../src/components/page/Find";

/**
 * sign: url에 따른 컴포넌트
 */
const SignComponent: NextPage = () => {
  const router = useRouter();
  const { action } = router.query;

  switch (action) {
    case MainRoute.SIGNUP:
      return <SignUp />;
      break;
    case MainRoute.FIND:
      return <Find />;
  }
};

const SignUpPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>MK SOLUTION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WholeWrapper minHeight={`100vh`} ju={`space-between`}>
        <Header />
        <SignComponent />
        <Footer />
      </WholeWrapper>
    </>
  );
};

export default SignUpPage;

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (context.req.cookies.mk_token) {
    return {
      redirect: {
        permanent: false,
        destination: "/view/main",
      },
    };
  }
};
